# Generated by Django 3.1 on 2020-11-11 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201111_1120'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='postal_coe',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
