# Generated by Django 3.1 on 2020-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('image', models.ImageField(default=None, upload_to='media/gallery/')),
                ('description', models.TextField()),
                ('design', models.CharField(choices=[('Interiors', 'INTERIORS'), ('Exteriors', 'EXTERIORS')], default=None, max_length=9)),
            ],
            options={
                'verbose_name_plural': 'Gallery',
            },
        ),
    ]
