# Generated by Django 3.1 on 2020-10-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='img',
            options={'verbose_name_plural': 'Images'},
        ),
    ]
