# Generated by Django 3.1 on 2020-09-07 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Main Content',
            },
        ),
        migrations.CreateModel(
            name='Slides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
                ('image', models.ImageField(default=None, upload_to='media/slides/')),
            ],
            options={
                'verbose_name_plural': 'Slides',
            },
        ),
        migrations.CreateModel(
            name='SubContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
                ('image', models.ImageField(default=None, upload_to='media/content/')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Sub Content',
            },
        ),
    ]
