# Generated by Django 3.1 on 2020-09-03 12:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='added',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='home',
            name='description',
            field=models.TextField(default=None, max_length=400),
        ),
        migrations.AddField(
            model_name='home',
            name='design',
            field=models.CharField(choices=[('Interiors', 'INTERIORS'), ('Exteriors', 'EXTERIORS')], default=None, max_length=9),
        ),
        migrations.AddField(
            model_name='home',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
