# Generated by Django 3.1 on 2020-10-08 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubContent',
        ),
    ]
