# Generated by Django 3.1 on 2020-09-04 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20200903_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=28)),
                ('description', models.TextField(default=None, max_length=400)),
                ('added', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
