# Generated by Django 3.1 on 2020-09-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='homecontent',
            name='image',
            field=models.ImageField(default=None, upload_to='media/'),
        ),
    ]
