# Generated by Django 3.1 on 2020-09-04 17:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homecontent_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
                ('description', models.TextField(default=None, max_length=1500)),
                ('added', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='SubContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=28)),
                ('image', models.ImageField(default=None, upload_to='media/')),
                ('description', models.TextField(default=None, max_length=1500)),
                ('added', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.DeleteModel(
            name='HomeContent',
        ),
    ]
