# Generated by Django 3.1 on 2020-10-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furnitures', '0002_product_sku'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
