# Generated by Django 3.1 on 2020-11-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0002_auto_20201104_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='checkout_session_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
