# Generated by Django 3.1 on 2020-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0003_auto_20201104_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='address',
            field=models.TextField(null=True),
        ),
    ]
