# Generated by Django 3.1 on 2020-09-15 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200915_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Interiors', 'INTERIORS'), ('Exteriors', 'EXTERIORS')], default=None, max_length=9),
        ),
    ]
